name: ob_component
description: A new Flutter package project.
version: 1.2.1
homepage: https://gitlab.ddyhr.com/clients/ob-components

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bot_toast: 4.0.3
  flutter_screenutil: 5.7.0
  wechat_assets_picker: 8.4.1
  pull_to_refresh: 2.0.0
  intl: 0.18.0
  image_picker: 0.8.7
  get:
    git:
      url: https://gitlab.ddyhr.com/clients/getx
      ref: 'ff6f3897646990f4d28a229747b8993c596e665a'
  ob_com_png:
    path: ../../module/ob_com_png/
  flutter_vibrate: ^1.3.0

dev_dependencies:
  lint: ^1.5.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/loading/
    - assets/images/icon/
  fonts:
    - family: DIN-Medium
      fonts:
        - asset: assets/fonts/DIN-Medium.otf
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
