class CacheList {
  static Map<String, int> list = {
    /// 首页
    '/game/ty/hotMatches': -1,
    '/game/zr/queryHotTables': -1,
    '/game/dj/obRecommend': -1,
    '/game/cp/getHotResultList': -1,
    '/game/dy/getGameConfigTop10': -1,
    '/game/queryGameLatest': -1,
    '/game/queryGameRank': -1,
    '/game/queryGameTopic': -1,
    '/gameModule/recommend': -1,

    "/gameModule/getGameModule": -1,
    "/config/clientConfigAll": -1,
    "/game/getPlatfromGame": -1,
    "/game/ty/videos": -1,
    "/gameModule/collect": -1,
    // "/member/infoAll": -1,
    "/messageCenter/selectAnnounceList": -1,
    "/game/getGameTopicDetail": -1,
    "/game/zr/queryAllTables": -1,
    "/game/dy/getGameConfigList": -1,
    "/game/dj/getMatchType": -1,
    "/game/dj/queryRecommendByGameId": -1,
    "/game/ty/matches": -1,
    "/game/qp/queryGameList": -1,
    // "/game/queryGameByGameName": -1,
    // "/messageCenter/selectNoticeList": -1,
    // "/messageCenter/selectAnnouncementList": -1,
    // "/messageCenter/selectBonusList": -1,
    "/discount/activityType": -1,
    "/discount/tag": -1,
    "/discount/discountActivity": -1,
    "/discount/sponsor": -1,
    "/game/queryGameAssortList": -1,
    "/game/queryMyCollectGames": -1,
    "/game/queryGameListByAssortId": -1,
    "/searchConfig/list": -1,
    "/messageCenter/hasUnReceivedBonus": -1,
    "/gameModule/getGameConfigAll": -1,
    "/help/all": -1,
    //"/game/login": -1,
    "/game/dj/enterGame": -1,
    "/game/ty/enterGame": -1,
    "/game/zr/forwardGame": -1,

    //  "/topImages/getTopImages": -1,
    // "/mb/depositWithdraw/user/allBalance": -1,
    // "/mb/depositWithdraw/select": -1,
    // "/topImages/setCurrentTopImages": -1,
    // "/topImages/deleteImages": -1,
    // "/obDiscountActivity/queryDiscountActivity": -1,
    // "/userApi/sendPhoneCode": -1,
    // "/userApi/uploadSubmit": -1,
    // "/user/updateRealName": -1,
    // "/userApi/addOverflowMember": -1,
    // "/userApi/selectMemberWithdrawAbleInfo": -1,
    // "/user/sendEmailCode": -1,
    // "/userApi/selectVipInfo": -1,
    // "/userApi/selectMemberAccount": -1,
    // "/userApi/selectVipLevel": -1,
    // "/game/dj/queryRecommendByGameId": -1,
    // "/game/dj/enterGame": -1,
    // "/game/queryGameLatest": -1,
    // "/game/ty/enterGame": -1,
    // "/game/withdraw": -1,
    // "/game/dj/obRecommend": -1,
    // "/game/login": -1,
    // "/game/queryGameRank": -1,
    // "/game/zr/login": -1,
    // "/game/zr/queryGameTypes": -1,
    // "/game/getPlatfromGame": -1,
    // "/game/getGameTopicDetail": -1,
    // "/game/ty/hotMatches": -1,
    // "/game/queryGameListByAssortId": -1,
    // "/game/cp/getAllResultList": -1,
    // "/game/zr/queryHotTables": -1,
    // // "/game/maintainMyCollect": -1,
    // "/game/queryPlatformGames": -1,
    // "/game/zr/queryAllTables": -1,
    // "/game/zr/forwardGame": -1,
    // "/game/dy/getGameConfigList": -1,
    // "/game/dj/getMatchType": -1,
    // "/game/qp/queryGameList": -1,
    // "/game/balanceTransfer": -1,
    // "/game/queryGameAssortList": -1,
    // "/game/queryMyCollectGames": -1,
    // "/game/queryGameTopic": -1,
    // "/game/ty/videos": -1,
    // "/game/dy/getGameConfigTop10": -1,
    // "/game/queryGameByGameName": -1,
    // "/game/ty/matches": -1,
    // "/game/profitAndLossToday": -1,
    // "/game/getModuleConfig": -1,
    // "/game/cp/getHotResultList": -1,
    // "/enter/getAnnouncementDetail": -1,
    // "/enter/getNoticeDetail": -1,
    // "/enter/selectAnnouncement": -1,
    // "/enter/selectNotice": -1,
    // "/enter/updateMessageStatus": -1,
    // "/gameModule/recommend": -1,
    // "/gameModule/getGameConfigAll": -1,
    // "/gameModule/getGameModule": -1,
    // "/gameModule/collect": -1,
    // "/help/all": -1,
    // "/geetest/firstRegister": -1,
    // "/geetest/secondValidate": -1,
    // "/sendMobileMessages": -1,
    // "/member/password/update": -1,
    // "/clientAddress": -1,
    // "/verificationCodeLogin": -1,
    // "/member/infoAll": -1,
    // "/depositAndWithdrawal/selectDeposit": -1,
    // "/depositAndWithdrawal/selectWithdrawal": -1,
    // "/discount/discountActivity": -1,
    // "/discount/tag": -1,
    // "/discount/activityType": -1,
    // "/manual/discount/receiveDiscount": -1,
    // "/discount/sponsor": -1,
    // "/discount/vip": -1,
    // "/userDeposit/user/deposit": -1,
    // "/tryMemberLogin": -1,
    // "/member/info": -1,
    // "/userDeposit/user/cancelDeposit": -1,
    // "/userDeposit/user/depositDetail": -1,
    // "/userWithdraw/user/withdraw": -1,
    // "/userWithdraw/user/cash/balance": -1,
    // "/userWithdraw/user/flowDetails": -1,
    // "/accountMoney/balance/gameOne": -1,
    // "/accountMoney/merchantGame": -1,
    // "/accountMoney/noTransfer": -1,
    // "/account/balance/game": -1,
    // "/account/noTransfer": -1,
    // "/account/balance": -1,
    "/messageCenter/selectAllUnReadAmount": -1,
    // "/messageCenter/deleteMessage": -1,
    // "/messageCenter/selectAnnouncementList": -1,
    // "/messageCenter/hasUnReceivedBonus": -1,
    // "/messageCenter/selectBonusList": -1,
    // "/messageCenter/selectRespectiveUnReadAmount": -1,
    // "/messageCenter/selectBonusUnReadAmount": -1,
    // "/messageCenter/selectNoticeList": -1,
    // "/messageCenter/selectAnnounceList": -1,
    // "/messageCenter/selectAnnouncementUnReadAmount": -1,
    // "/messageCenter/updateMessageStatus": -1,
    // "/messageCenter/selectNoticeUnReadAmount": -1,
    // "/firstDeposit/activityDeposit": -1,
    // "/firstDeposit/getUserVipActivityInfo": -1,
    // "/memberVipGrade/queryVipGrade": -1,
    // "/valetRecharge/generateRecharge": -1,
    // "/typay/deposit/getExchange": -1,
    // "/typay/deposit/view": -1,
    // "/typay/withdraw/list": -1,
    // "/typay/deposit/banks": -1,
    // "/typay/deposit/list": -1,
    // "/gameDeposit/streamDetails": -1,
    // "/gameDeposit/deposit": -1,
    // "/gameDeposit/depositCount": -1,
    // "/config/startPage": -1,
    // "/config/publicResources": -1,
    // "/config/depositConfig": -1,
    // "/config/clientConfigAll": -1,
    // "/gameRecord/query/game": -1,
    // "/gameRecord/query/all": -1,
    // "/userBank/query": -1,
    // "/userBank/isVerified": -1,
    // "/userBank/verifiTwoElement": -1,
    // "/userBank/sendMobileMessages": -1,
    // "/commission/commissionPaymentOrder": -1,
    // "/commission/commissionHistory": -1,
    // "/multiAgent/member/queryMemberNetAmountDetail": -1,
    // "/rebate/payRebate": -1,
    // "/rebate/detailPage": -1,
    // // "/multiAgent/member/queryMemberNetAmount": -1,
    // "/rebate/unReceive": -1,
    // "/commission/currMonthCommissionBudget": -1,
    // // "/lowerMember/list": -1,
    // "/lowerMember/gameRecords": -1,
    // "/commission/vipRule": -1,
    // "/vipGrade/getVipGrade": -1,
    // "/feedBack/feedBackList": -1,
    // "/feedBack/addFeedBack": -1,
    // "/searchConfig/list": -1,
    // "/bonusMsg/select": -1,
    // "/accessRecord/withdrawal": -1,
    // "/accessRecord/deposit": -1,
    // "/order/deposit": -1,
    // "/obDiscount/query/config": -1
  };
}
