name: ob_com_base
description: ob_com_base.
version: 1.0.0
repository: https://github.com
issue_tracker: https://github.com
homepage: https://github.com
documentation: https://github.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 5.7.0
  sp_util: ^2.0.3
  dio: 5.1.1
  flutter_swiper: ^1.1.6
  convert: ^3.0.1
  pull_to_refresh: ^2.0.0
  event_bus: ^2.0.0
  encrypt: ^5.0.0
  url_launcher: ^6.0.4
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.1.2
  image_picker: 0.8.7
  wechat_assets_picker: 8.4.1
  like_button: ^2.0.2
  sprintf: 7.0.0
  common_utils: ^2.0.2
  platform_device_id: ^1.0.1
  pretty_dio_logger: "^1.1.1"
  heic_to_jpg:
    git:
      url: https://gitlab.ddyhr.com/foundation/flutter_heic_to_jpg.git
      ref: 'b57a424c501092d28552b755c394e43e280f19ab'
  image_gallery_saver:
    git:
      url: https://gitlab.ddyhr.com/foundation/image_gallery_saver.git
  flutter_image_compress:
    git:
      url: https://gitlab.ddyhr.com/foundation/flutter_image_compress.git
      ref: '3931719500e7bd0c3c2f3eeedece166dbd6a86f3'
  flutter_vibrate: ^1.3.0
  auto_animated: ^3.0.0
  app_installer: ^1.1.0
  barcode_widget: ^2.0.3
  permission_handler: 10.2.0
  tuple: ^2.0.1
  auto_size_text: ^2.1.0
  visibility_detector: ^0.2.0
  path_provider: ^2.0.2
  custom_navigation_bar: ^0.8.2
  flutter_matrix_html: 1.1.0
  flutter_staggered_animations: "^1.0.0"
  flavor: ^2.0.0
  cool_ui: 1.3.0
  lpinyin: ^2.0.2
  universal_html: ^2.0.8
  flutter_slidable: ^1.2.0
  lottie: 1.3.0
  device_info_plus: 8.1.0
  connectivity_plus: 3.0.3
  params:
    git:
      url: https://gitlab.ddyhr.com/clients/melos_repo.git
      ref: justice_api
      path: api/params
  exception:
    git:
      url: https://gitlab.ddyhr.com/clients/melos_repo.git
      ref: justice_api
      path: api/exception
  models:
    git:
      url: https://gitlab.ddyhr.com/clients/melos_repo.git
      ref: justice_api
      path: api/models
  config:
    git:
      url: https://gitlab.ddyhr.com/clients/melos_repo.git
      ref: justice_api
      path: api/config
  user:
    git:
      url: https://gitlab.ddyhr.com/clients/melos_repo.git
      ref: justice_api
      path: api/user
  webview_flutter:
    git:
      url: https://gitlab.ddyhr.com/clients/ob_webview
  udid:
    git:
      url: https://gitlab.ddyhr.com/foundation/udid

  get_version:
    git:
      url: https://github.com/Creky/get_version.git

  get:
    git:
      url: https://gitlab.ddyhr.com/clients/getx
      ref: 'ff6f3897646990f4d28a229747b8993c596e665a'

  repository:
    git:
      url: https://gitlab.ddyhr.com/clients/ob_network_service
      ref: develop_package

  ob_component:
    git:
      url: https://gitlab.ddyhr.com/clients/ob-components
      ref: dev-3.0

dependency_overrides:
  js: 0.6.7
  lottie: 2.3.1
  xml: 6.2.2
  collection: 1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  build_runner:
  flutter_gen_runner:
  ob_com_png:
    path: ../ob_com_png/

flutter_gen:
  output: lib/gen/
  line_length: 80
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors_theme.xml
      - assets/color/colors_app.xml

flutter:
  uses-material-design: true

  fonts:
    - family: DIN-Medium
      fonts:
        - asset: assets/fonts/DIN-Medium.otf
    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf
