// ignore_for_file: constant_identifier_names

abstract class AppRoutes {
  static const String HOME = "/";
  static const String RAKING = "/raking"; //盒子详情页面
  static const String WEB = "/web"; //H5页面
  static const String LOGIN = "/login"; //login登录页面
  static const String THIRD_PARTY = "/third_party"; //第三方登录
  static const String LOGIN_ERROE = "/login_error"; //login登录异常页面
  static const String FIND_PASSWORD = "/find_password"; //login登录异常页面
  static const String MESSAGE = '/message'; //消息
  static const String MESSAGE_INFO = '/message_info'; //消息
  static const String BET_HISTORY = "/bet_history"; //投注记录
  static const String BET_DETAIL_LIST = "/bet_detail_list"; //投注记录分类型列表页面
  static const String ACCOUNT = '/account'; //
  static const String BANK = '/bank'; // 添加银行卡
  static const String CRYPTOCURRENCY = '/cryptocurrency'; // 添加虚拟币账户
  static const String PROFILE = '/profile'; // 添加银行卡第二步
  static const String USDT = '/usdt'; // 添加usdt账户
  static const String TRANSFER = '/transfer'; // 转账
  static const String CAPITAL = '/capital'; // 资金
  static const String WALLET = '/wallet'; // 场馆详情
  static const String GAME_TRANSFER = '/game_transfer'; // 游戏场馆进入转账
  static const String WITHDRAW = '/withdraw'; // 取款
  static const String BIND_EMAIL = '/bind_email'; // 绑定邮箱
  static const String BIND_PHONE_NUMBER = '/bind_phone_number'; // 绑定电话号码
  static const String SETTING = '/setting'; // 设置
  static const String USER_TOGGLE = '/user_toggle'; // 切换用户
  static const String USER_ADD = '/user_add'; // 切换添加与登录
  static const String LOCK_SETTING = '/lock_setting'; // 锁屏设置
  static const String VERIFY_INDETITY = '/verify_identity'; // 身份验证
  static const String PHONE_VERIFY_INDETITY = '/phone_verify_identity'; // 电话身份验证
  static const String EMAIL_VERIFY_INDETITY = '/email_verify_identity'; // 电话身份验证
  static const String UPDATE_PASSWORD = '/update_password'; // 修改密码
  static const String USER_PROFILE = '/user_profile'; // 修改资料
  static const String Avatar_Clip = '/avatar_clip'; // 头像裁剪
  static const String DEPOSIT = '/deposit';
  static const String DEPOSIT_EASY = '/deposit_easy';
  // 页面暂时不作废！！！
  //static const String DEPOSIT_RESULT = '/deposit_result'; // 虚拟币充值结果
  static const String THIRD_DEPOSIT = '/third_deposit'; // 充值信息
  static const String SEARCH = '/search'; //搜索
  static const String MY_WALLET = '/my_wallet'; // 我的钱包
  static const String LEDGER_RECORD = '/ledger_record'; // 额度记录
  static const String LEDGER_DETAIL = '/ledger_detail'; // 额度记录详情
  static const String ACCESS_RECORD = '/access_record'; // 存取记录
  static const String ACCESS_RECORD_DETAIL = '/access_record_detail'; // 存取记录
  static const String CONTACT_US = '/cantact_us'; //联系我们
  static const String FEEDBACK = '/feedback'; //意见反馈
  static const String MY_FEEDBACK = '/my_feedback'; //我的反馈
  static const String DEPOSIT_COURSE = '/deposit_course'; //存款教程
  static const String COMMON_COURSE = '/common_course'; //教程页
  static const String HELP_EMPTY = '/help_empty'; //教程空白页
  static const String SETUP_GESTURE_PASSWORD = '/setup_gesture_password'; //设置手势密码
  static const String CONFIRM_GESTURE_PASSWORD = '/confirm_gesture_password'; //确认手势密码
  static const String GAME_INTRODUCE = '/game_introduce'; //游戏介绍
  static const String START = '/start'; //启动页
  static const String FALSH_SCREEN = '/falsh_screen'; //闪屏
  static const String GAME = '/game'; //游戏
  static const String REGISTER_TEXT = '/register_text'; //条款与隐私政策
  static const String DISCOUNT_DETAIL = '/discount_detail'; //优惠详情
  static const String INVITE_DETAIL = '/invite_detail'; //邀请活动详情
  static const String INVITE_APPLY = '/invite_apply'; //邀请活动之申请
  static const String ACTIVITY_RECORD = '/activity_record'; //活动记录
  static const String SPORTS = '/sports'; //体育详情页
  static const String BACCARAT = '/baccarat'; //真人详情页
  static const String QP = '/qp'; //棋牌详情页
  static const String RANKING = '/ranking'; //排行详情页
  static const String AGGREGATE = '/aggregate'; //全家桶详情页
  static const String LOTTERY = '/lottery'; //彩票详情页
  static const String ELECTRONIC = '/electronic'; //电子情页
  static const String NEWGAME = '/newGame'; //最新游戏情页
  static const String ESPORTS = '/esports'; //电竞情页
  static const String VIP_LEVEL = '/vip_level'; //VIP等级
  static const String VIP_LEVEL_DETAIL = '/vip_level_detail'; //VIP等级详情
  static const String GESTURE_LOGIN = '/gesture_login'; //手势密码登陆
  static const String ONBOARDING = '/welcome'; //app引导页
  static const String SPLASH = '/splash'; //app闪屏页
  static const String GESTURE_LOGIN_PAGE = '/gesture_loginPage'; //手势密码登陆
  static const String limitIpPage = '/LimitIpPage'; //ip限制
  static final String h5DownloadPage = '/h5DownloadPage'; //h5下载引导页
  static const String RESET_PASSWORD = '/reset_password'; //重置密码
  static const String AGENT_WEB = "/agent_web"; //H5页面
  static const String CRYPTOCURRENCY_DEPOSIT_WIKI = '/agent_n_cryptocurrency_deposit_wiki'; //虚拟币充值
  static const String AGENT_N_RECHARGE_WITHDRAWAL = '/agent_n_recharge_withdrawal'; //充提记录
  static const String AGENT_N_ACCOUNT_CHARGE = '/agent_n_account_charge'; //额度充值
  static const String AGENT_N_COMMISSION_WITHDRAWALS = '/agent_n_commission_withdrawals'; //多级代佣金取款
  static const String AGENT_N_ADD_BANK = '/agent_n_add_bank'; //多级代添加银行卡
  static const String AGENT_N_ADD_VIRTUAL = '/agent_n_add_virtual'; //多级代添加虚拟账户

  static const String AGENT_COMMISSION_WITHDRAWALS = '/agent_commission_withdrawals'; //多级代佣金取款
  static const String AGENT_ADD_BANK = '/agent_add_bank'; //多级代添加银行卡
  static const String AGENT_ADD_VIRTUAL = '/agent_add_virtual'; //多级代添加虚拟账户
  static const String AGENT_WITHDRAWALS_RECORD = '/agent_withdrawals_record'; //多级代添加银行卡
  static const String AGENT_LIST = '/agent_list'; // 代理列表
  static const String AGENT_ADD = '/agent_add'; // 新增代理
  static const String AGENT_CONTRACT = '/agent_contract'; // 契约管理
  static const String AGENT_CONTRACT_RULE = '/agent_contract_rule'; // 契约规则 新增契约 修改契约 重订契约
  static const String AGENT_CONTRACT_RULE_BOTH = '/agent_contract_rule_both'; // 契约规则 新增契约 修改契约 重订契约
  static const String AGENT_CONTRACT_REUSE = '/agent_contract_reues'; // 复用契约
  static const String AGENT_MEMBER_LIST = '/agent_member_list'; //会员列表
  static const String AGENT_N_NEW_MEMBER = '/agent_n_new_member'; //新增会员
  static const String AGENT_N_OVER_APPLY = '/agent_n_over_apply'; //代理溢出申请
  static const String AGENT_N_FILL_IN_MATERIALS = '/agent_n_fill_in_materials'; //填写溢出申请资料
  static const String AGENT_N_MEMBER_DEPOSIT = '/agent_n_member_deposit'; //代会员存款
  static const String AGENT_N_AGENT_TRANSFER = '/agent_n_agent_transfer'; //代理转账
  static const String AGENT_N_TRANSFER_RECORDS = '/agent_n_transfer_records'; //转账记录
  static const String AGENT_HOME = '/agent_home'; //代理首页
  static const String JOIN_US_AGENT = '/join_us_agent'; //加入代理
  static const String AGENT_PROFITLOSS_MEMBER = '/agent_profit_loss_member'; //会员盈亏
  static const String AGENT_PROFITLOSS_DETAILS = '/agent_profit_loss_details'; //盈亏明细
  static const String AGENT_PROFITLOSS_DAILY = '/agent_profit_loss_daily'; //每日盈亏明细
  static const String AGENT_PROFITLOSS_AGENT = '/agent_profit_loss_agent'; //代理盈亏
  static const String AGENT_PROFITLOSS_AGENT_DETAILS = '/agent_profit_loss_agent_details'; //代理盈亏明细
  static const String AGENT_PROFITLOSS_AGENT_DAILY = '/agent_profit_loss_agent_daily'; //代理每日盈亏明细
  static const String AGENT_REBATES_MANAGEMENT = '/agent_rebates_management'; //返点管理
  static const String AGENT_REBATES_NEXT = '/agent_rebates_next'; //下级返点
  static const String AGENT_N_ACCOUNT_CHANGE_DETAILS = '/agent_n_account_change_details'; //明细
  static const String AGENT_N_MESSAGE = '/agent_n_message'; //多级代理消息中心
  static const String AGENT_N_ACCOUNT_CHANGE_XIQNG_QING = '/agent_n_account_change_xiqng_qing'; //代理-账变详情
  static const String AGENT_N_COMMISSION_MANAGE = '/agent_n_commission_manage'; //代理-佣金管理
  static const String AGENT_N_PROMOTION_RECORD = '/agent_n_promition_record'; //代理优惠记录
  static const String AGENT_N_GAME_RECORD = '/agent_n_game_record'; //代理游戏记录
  static const String AGENT_N_GAME_RECORD_DETAIL = '/agent_n_game_record_detail'; //代理游戏记录详情

  static const String AGENT_N_SURROGATE_RECORD = '/agent_n_surrogate_record'; //代存记录
  static const String AGENT_N_POPULARIZE = '/agent_n_popularize'; //代理-推广
  static const String AGENT_N_EDIT_QRCODE = '/agent_n_edit_qrcode'; //编辑二维码
  static const String Agent_N_POPULARIZE_MATERIAL = '/agent_n_popularize_material'; //推广素材
  static const String AGENT_N_SEARCH_GEN = '/agent_n_search_gen'; //AgentNSearchViewPage
  static const String AGENT_CONTACTS_MINE = '/agent_contacts_mine'; //联系方式
  static const String AGENT_VIP_ENJOY = '/agent_vip_enjoy'; //vip专享

  static const String AGENT_N_MY_CONTRACT = '/agent_n_my_contract'; //我的契约
  static const String AGENT_N_MEMBER_PAY_PASSWORD = '/agent_n_member_pay_password'; //支付密码
  static const String AGENT_N_DEPOSIT_RESULT = '/agent_n_deposit_result'; // 代理充值结果
  static const String AGENT_N_THIRD_DEPOSIT = '/agent_n_third_deposit'; // 代理充值信息
  static const String AGENT_N_EDIT_MATERIAL = '/agent_n_edit_material'; //编辑二维码
  static const String Agent_N_ACCESS_RECORD_DETAIL = '/agent_n_access_record_detail'; // 存取记录
  static const String AGENT_N_HISTORY_COMMISSION_PAY = '/agent_n_history_commission_pay';
  static const String AGENT_N_MESSAGE_DETAIL = '/agent_n_message_detail';
  static const String Agent_N_DEPOSIT_COURSE = '/agent_n_deposit_course'; //存款教程
  static const String MEMBER_DEPOSIT_RECORD = "/member_deposit_record"; //会员存款记录
  static const String WEB_IFRAME = "/web_iframe"; //web端的iframe页面
  static const String SET_REAL_NAME = "/set_real_name"; //设置姓名
  static const String LANG_SETTING = "/lang_setting"; //选择语言
  static const String Electronic_Games = "/electronic_games"; //选择语言
  static const String VENUE_LIST = "/venue_list"; //场馆列表
  static const String GAME_GRID = "/game_grid"; //游戏列表
  static const String My_Collection = "/my_collection"; //我的收藏
  static const String VenueGameList = "/venue_game_list"; //我的收藏




}
