name: repository
description: A starting point for Dart libraries or applications.
version: 1.7.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  collection: 1.17.0

dev_dependencies:
  dio: 5.1.1
  pedantic: ^1.10.0
  test: ^1.16.0
  sp_util: ^2.0.3
  pretty_dio_logger: "^1.1.1"
  path_provider: ^2.0.2
  flutter_easyloading: ^3.0.0
  get: ^4.6.1
  equatable: ^2.0.3
  hive_generator: any
  tuple: ^2.0.0
  event_bus: ^2.0.0
  encrypt: ^5.0.0
  archive: ^3.3.0
  socket_io_client: ^1.0.1
  sqflite: ^2.0.0+4
  collection: 1.17.0
  neat_periodic_task: ^2.0.0
  stash: ^2.0.2
  stash_file: ^2.0.2
  worker_manager: ^4.2.4
  device_info_plus: 3.2.3
  platform_device_id: ^1.0.1
  udid:
    git:
      url: https://gitlab.ddyhr.com/foundation/udid

  yaml:

