import 'package:get/get.dart';

// 银行卡(1, "银行卡"),
// 信用卡(2, "信用卡"),
// 虚拟币(3, "虚拟币"),
// 支付宝(4, "支付宝"),
// 微信(5, "微信"),
// 其他(6, "其他"),

// 银行卡转卡(1, "银行卡转卡", DepositType.银行卡),
// 信用卡充值(2, "信用卡充值", DepositType.信用卡),
// 虚拟币充值(3, "虚拟币充值", DepositType.虚拟币),
// 支付宝转卡(4, "支付宝转卡", DepositType.支付宝),
// 支付宝扫码(5, "支付宝扫码", DepositType.支付宝),
// 微信转卡(6, "微信转卡", DepositType.微信),
// 微信扫码(7, "微信扫码", DepositType.微信),
// 云闪付(8, "云闪付", DepositType.其他),
// 京东支付(9, "京东支付", DepositType.其他)
// 银行卡收银台_ALL(29, "不指定银行", DepositType.银行卡收银台),
// 银行扫码收银台_ALL(30, "不指定银行", DepositType.银行扫码收银台),
// SuperQuickCode(31, "极速快扫", DepositType.其他),

//vietinbankipay(10, "vietinbankipay", DepositType.其他),
// vietcombank(11, "vietcombank", DepositType.其他),
// techcombank(12, "techcombank", DepositType.其他),
// zalo(13, "zalo", DepositType.其他),
// momo(14, "momo", DepositType.其他),
// pvbank(15, "pvbank", DepositType.其他),
// tpbank(16, "tpbank", DepositType.其他),
// depositcard(17, "depositcard", DepositType.其他),
// vpbank(18, "vpbank", DepositType.其他),
// vibbank(19, "vibbank", DepositType.其他),
// mbbank(20, "mbbank", DepositType.其他),
// vtpay(21, "vtpay", DepositType.其他),
// acbbank(22, "acbbank", DepositType.其他),
// bidv(23, "bidv", DepositType.其他),
// BIDV直连(24, "BIDV", DepositType.银行卡),
// VTB直连(25, "VTB", DepositType.银行卡),
// MB直连(26, "MB", DepositType.银行卡),
// ACB直连(27, "ACB", DepositType.银行卡),
// VCB直连(28, "VCB", DepositType.银行卡),
//银行卡收银台_ALL(29, "不指定银行", DepositType.银行卡收银台),
// 银行扫码收银台_ALL(30, "不指定银行", DepositType.银行扫码收银台),
// SuperQuickCode(31, "极速快扫", DepositType.其他),
// ViettelPay(32, "ViettelPay", DepositType.其他),
Map<int, dynamic> get PayTypeNameDic => {
      1: 'pay_type_bank_card_transfer'.tr,
      2: 'xinK'.tr,
      11: 'pay_type_online_bankingto_public_account'.tr,
      110: 'pay_type_alipay_to_bank_card'.tr,
      4: 'pay_type_alipay_to_bank_card'.tr,
      112: 'pay_type_bank_card_recharge'.tr,
      //113: 'pay_type_cloud_quick_passto_bank_card'.tr,
      8: 'pay_type_cloud_quick_passto_bank_card'.tr,
      9: 'pay_jingdong'.tr,
      10: 'vietinbankipay'.tr,
      12: 'techcombank'.tr,
      13: 'zalo'.tr,
      14: 'bank_card_pay_momo'.tr,
      15: 'pvbank'.tr,
      16: 'tpbank'.tr,
      17: 'depositcard'.tr,
      18: 'vpbank'.tr,
      19: 'vibbank'.tr,
      20: 'mbbank'.tr,
      21: 'vtpay'.tr,
      22: 'acbbank'.tr,
      23: 'bidv'.tr,
      24: 'BIDV'.tr,
      25: 'VTB'.tr,
      26: 'MB'.tr,
      27: 'ACB'.tr,
      28: 'VCB'.tr,
      29: 'bank_card_pay_shou'.tr,
      30: 'bank_card_pay_shao'.tr,
      31: 'bank_card_pay_quik_shao'.tr,
      32: 'ViettelPay'.tr,
      114: 'pay_type_alipay_h5tobankcard'.tr,
      115: 'pay_type_we_chattransfercard'.tr,
      6: 'ledger_record_other'.tr,
      116: 'pay_type_jingdong_financial_payment'.tr,
      3: 'pay_type_virtual_currency'.tr,
      200: 'pay_type_union_paypayment'.tr,
      212: 'pay_type_quick_payment'.tr,
      213: 'pay_type_union_payscancode'.tr,
      214: 'pay_type_online_banking_to_pay'.tr,
      //312: 'pay_type_we_chatscancode'.tr,
      7: 'pay_type_we_chatscancode'.tr,
      313: 'pay_type_we_chat_h5'.tr,
      410: 'pay_type_alipay_h5'.tr,
      //411: 'pay_type_alipay_scan_code'.tr,
      5: 'pay_type_we_chattransfercard'.tr,
      511: 'pay_type_q_qscancode'.tr,
      512: 'pay_type_q-q-h5'.tr,
      610: 'pay_type_jingdong_scan_code'.tr,
      710: 'pay_type_cloud_quick_pass'.tr,
      910: 'pay_type_Alipay'.tr,
      911: 'pay_type_speedy_we_chat'.tr,
      912: 'pay_type_extreme_speed_card'.tr,
      913: 'non_fixed_amount_of_bank_card_transfer'.tr,
      1000: 'pay_type_douyin_red_packet'.tr,
      2010: 'pay_type_three_way_bank_card_transfer'.tr,
      2020: 'pay_type_three_way_alipaytransfercard'.tr,
      2030: 'pay_type_three_party_large_recharge'.tr,
      2040: 'pay_type_three_party_bank_card_transfer_information'.tr,
      2050: 'pay_type_three_party_cloud_flash_payment_transfer_card'.tr,
      2060: 'pay_type_small_amount_bank_card_transfer_card'.tr,
      2110: 'pay_type_u_s_d_tscancode'.tr,
      2120: 'pay_type_virtual_currency_recharge'.tr,
      2130: 'pay_type_currency_transfer'.tr,
      2140: 'pay_type_currency_exchange_virtual_currency'.tr,
      2150: 'pay_type_easy_coin_pay_virtual_currency'.tr,
      2160: 'pay_type_direct_q_rcode'.tr,
      2170: 'pay_type_card_payment'.tr,
      2220: 'pay_type_digital_yuan'.tr,
      5001: 'pay_type_valet_recharge'.tr,
    };

const PayTypeIconDic = {
  1: 'assets/images/icon/icon_deposit_bank_card.webp',
  2: 'assets/images/icon/icon_deposit_usdt.webp',
  11: 'assets/images/icon/icon_deposit_online_bank.webp',
  110: 'assets/images/icon/icon_deposit_alipay.webp',
  112: 'assets/images/icon/icon_deposit_bank_card.webp',
  //113: 'assets/images/icon/icon_deposit_yunshanfu.webp',
  8: 'assets/images/icon/icon_deposit_yunshanfu.webp',
  114: 'assets/images/icon/icon_deposit_alipay.webp',
  4: 'assets/images/icon/icon_deposit_alipay.webp',
  115: 'assets/images/icon/icon_deposit_wechat.webp',
  6: 'assets/images/icon/icon_deposit_wechat.webp',
  116: 'assets/images/icon/icon_deposit_jd.webp',
  //2: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  3: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  200: 'assets/images/icon/icon_deposit_unionpay.webp',
  212: 'assets/images/icon/icon_deposit_quick_payment.webp',
  213: 'assets/images/icon/icon_deposit_unionpay.webp',
  214: 'assets/images/icon/icon_deposit_online_bank.webp',
  //312: 'assets/images/icon/icon_deposit_wechat.webp',
  7: 'assets/images/icon/icon_deposit_wechat.webp',
  313: 'assets/images/icon/icon_deposit_wechat.webp',
  410: 'assets/images/icon/icon_deposit_alipay.webp',
  //411: 'assets/images/icon/icon_deposit_alipay.webp',
  5: 'assets/images/icon/icon_deposit_alipay.webp',
  511: 'assets/images/icon/icon_deposit_qq.webp',
  512: 'assets/images/icon/icon_deposit_qq.webp',
  610: 'assets/images/icon/icon_deposit_jd.webp',
  710: 'assets/images/icon/icon_deposit_yunshanfu.webp',
  910: 'assets/images/icon/icon_deposit_alipay.webp',
  911: 'assets/images/icon/icon_deposit_wechat.webp',
  912: 'assets/images/icon/icon_deposit_rapid_pay.webp',
  913: 'assets/images/icon/icon_deposit_bank_card.webp',
  1000: 'assets/images/icon/icon_deposit_bank_card.webp',
  2010: 'assets/images/icon/icon_deposit_bank_card.webp',
  2020: 'assets/images/icon/icon_deposit_alipay.webp',
  2030: 'assets/images/icon/icon_deposit_bank_card.webp',
  2040: 'assets/images/icon/icon_deposit_bank_card.webp',
  2050: 'assets/images/icon/icon_deposit_yunshanfu.webp',
  2060: 'assets/images/icon/icon_deposit_bank_card.webp',
  9: 'assets/images/icon/icon_deposit_bank_card.webp',
  2110: 'assets/images/icon/icon_deposit_usdt.webp',
  2120: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2130: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2140: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2150: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2160: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2170: 'assets/images/icon/icon_deposit_cryptocurrency.webp',
  2220: 'assets/images/icon/icon_deposit_bank_card.webp',
  5001: 'assets/images/icon/icon_deposit_customer_service.webp',
};
